/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package utp.restaurant.waiter.view;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import utp.restaurant.dao.ItemMenuDAO;
import utp.restaurant.dao.OrderDAO;
import utp.restaurant.model.ItemMenu;
import utp.restaurant.model.ItemOrder;
import utp.restaurant.utils.Validate;

/**
 *
 * @author dalia
 */
public class MenuDetails extends javax.swing.JDialog {

    private TakeOrderView root;

    private long itemMenu_id;

    private ItemMenuDAO imdao;

    private ItemMenu itemMenu;
    private ItemOrder itemOrder;

    private Validate vldt;
    private String action;

    public MenuDetails(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        vldt = new Validate();
        imdao = new ItemMenuDAO();

        action = "add";

        initComponents();

    }

    public void setRoot(TakeOrderView root) {
        this.root = root;
    }

    public void setAction(String action) {
        this.action = action;
    }

    public void setItemMenu_id(long itemMenu_id) {
        this.itemMenu_id = itemMenu_id;
    }

    public void setAtributes() {

        itemMenu = action.equals("add") ? imdao.get(itemMenu_id) : itemOrder.getItemMenu();

        //pintando el Label con el nombre
        jLBnameMenu.setText(itemMenu.getName());

        //pintando el label con la descripcion
        jTFDescription.setText(itemMenu.getDescription());

        //pintando el label con el icono
        jLBimageMenu.setIcon(new ImageIcon(getClass().getResource("/utp/restaurant/images/platillos/" + itemMenu.getImage())));

        jLBprecioPreview.setText("S/" + (action.equals("add") ? itemMenu.getPrice() : itemOrder.getTotal()));

        if (action.equals("edit")) {
            jTFAmount.setText(itemOrder.getAmount() + "");
        }

        jTFamountAddAmountListener();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTFDescription = new javax.swing.JTextField();
        jTFAmount = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLBnameMenu = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLBimageMenu = new javax.swing.JLabel();
        jLBdescripcion = new javax.swing.JLabel();
        jLBprecioPreview = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(249, 242, 228));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTFDescription.setBackground(new java.awt.Color(249, 242, 228));
        jTFDescription.setForeground(new java.awt.Color(51, 51, 51));
        jTFDescription.setBorder(null);
        jPanel1.add(jTFDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 360, 30));

        jTFAmount.setBackground(new java.awt.Color(249, 242, 228));
        jTFAmount.setForeground(new java.awt.Color(51, 51, 51));
        jTFAmount.setText("1");
        jTFAmount.setBorder(null);
        jTFAmount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFAmountMouseClicked(evt);
            }
        });
        jTFAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFAmountActionPerformed(evt);
            }
        });
        jTFAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFAmountKeyTyped(evt);
            }
        });
        jPanel1.add(jTFAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 160, 30));

        jButton1.setBackground(new java.awt.Color(86, 42, 35));
        jButton1.setForeground(new java.awt.Color(249, 242, 228));
        jButton1.setText("CANCELAR");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, 100, 30));

        jButton2.setBackground(new java.awt.Color(86, 42, 35));
        jButton2.setForeground(new java.awt.Color(249, 242, 228));
        jButton2.setText("AGREGAR");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 90, 30));

        jLabel5.setBackground(new java.awt.Color(86, 42, 35));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(86, 42, 35));
        jLabel5.setText("DESCRIPCION");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, 20));

        jLBnameMenu.setBackground(new java.awt.Color(86, 42, 35));
        jLBnameMenu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLBnameMenu.setForeground(new java.awt.Color(86, 42, 35));
        jPanel1.add(jLBnameMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(86, 42, 35));
        jSeparator2.setForeground(new java.awt.Color(86, 42, 35));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 360, 12));

        jSeparator3.setBackground(new java.awt.Color(86, 42, 35));
        jSeparator3.setForeground(new java.awt.Color(86, 42, 35));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 170, 12));

        jLabel9.setBackground(new java.awt.Color(86, 42, 35));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(86, 42, 35));
        jLabel9.setText("PRECIO A PAGAR");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, -1, 20));
        jPanel1.add(jLBimageMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 350));

        jLBdescripcion.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jLBdescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 370, 30));

        jLBprecioPreview.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLBprecioPreview.setForeground(new java.awt.Color(86, 42, 35));
        jLBprecioPreview.setText("S/0.0");
        jPanel1.add(jLBprecioPreview, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 170, 30));

        jLabel10.setBackground(new java.awt.Color(86, 42, 35));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(86, 42, 35));
        jLabel10.setText("CANTIDAD");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, 20));

        jSeparator4.setBackground(new java.awt.Color(86, 42, 35));
        jSeparator4.setForeground(new java.awt.Color(86, 42, 35));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 160, 12));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        root.getjBTNadd().setEnabled(false);
        dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        //PRECIO
        String str = jTFAmount.getText();
        vldt.setElement(str)
                .isRequired("La cantidad es obligatorio")
                .isInt("tiene que ser numerico")
                .greaterThan(0, "La cantidad tiene que ser mayor a 0");

        if (!vldt.exec()) {
            showMessage(vldt.getMessage());
            jTFAmount.requestFocus();
            return;
        }
        int cantidad = Integer.parseInt(str);

        //DESCRIPCION
        String descripcion = jTFDescription.getText();

        if (action.equals("add")) {

            try {
                //Creando nuevo objeto ItemOrder
                ItemOrder newItemOrder = new ItemOrder(cantidad, descripcion, itemMenu);

                root.setItemOrder(newItemOrder);
                showMessage("Platillo ordenado correctamente");

            } catch (Exception e) {

                showMessage("Platillo no ordenado");

            }

        } else if (action.equals("edit")) {

            try {
                //Creando nuevo objeto ItemOrder
                ItemOrder updateItemOrder = new ItemOrder(cantidad, descripcion, itemOrder.getItemMenu());

                //iodao.update(itemOrder_id, newItemOrder);
                root.updateOrderItem(updateItemOrder);
                showMessage("Platillo ordenado actualizado");

            } catch (Exception e) {

                showMessage("Platillo ordenado no actualizado");

            }

        }

        root.renderItemOrderTable();
        root.getjBTNadd().setEnabled(false);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    public void showMessage(String msj) {
        JOptionPane.showMessageDialog(rootPane, msj);
    }
    private void jTFAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFAmountActionPerformed


    }//GEN-LAST:event_jTFAmountActionPerformed

    private void jTFAmountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFAmountMouseClicked


    }//GEN-LAST:event_jTFAmountMouseClicked

    public void jTFamountAddAmountListener() {
        jTFAmount.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                updatePricePreview();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updatePricePreview();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                updatePricePreview();
            }

            private void updatePricePreview() {

                String amount = jTFAmount.getText();
                //obteniendo la cantidad
                double cantidad = amount.equals("") ? 0 : Double.parseDouble(amount);

                //Pintando en el label
                if (action.equals("add")) {

                    jLBprecioPreview.setText("S/" + (itemMenu.getPrice() * cantidad));

                } else if (action.equals("edit")) {

                    jLBprecioPreview.setText("S/" + (itemOrder.getItemMenu().getPrice() * cantidad));

                }

            }

        });

    }

    private void jTFAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFAmountKeyTyped


    }//GEN-LAST:event_jTFAmountKeyTyped

    public ItemOrder getItemOrder() {
        return itemOrder;
    }

    public void setItemOrder(ItemOrder itemOrder) {
        this.itemOrder = itemOrder;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MenuDetails dialog = new MenuDetails(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLBdescripcion;
    private javax.swing.JLabel jLBimageMenu;
    private javax.swing.JLabel jLBnameMenu;
    private javax.swing.JLabel jLBprecioPreview;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTFAmount;
    private javax.swing.JTextField jTFDescription;
    // End of variables declaration//GEN-END:variables
}
